FROM simonswine/jenkins-ubuntu:saucy
MAINTAINER Christian Simon <simon@swine.de>
# Install Latex Stuff
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install biblatex groff-base latex-beamer latex-xcolor latexmk libalgorithm-merge-perl liblocale-gettext-perl libnewt0.52 libpango1.0-0:amd64 libptexenc1 libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl luatex mawk nano preview-latex-style tex-common texlive-base texlive-binaries texlive-fonts-recommended texlive-generic-recommended texlive-lang-german texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-pstricks texlive-xetex git lmodern biber
