FROM simonswine/jenkins-debian:wheezy
MAINTAINER Christian Simon <simon@swine.de>
# Install OpenWRT Building tools
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ant wget gawk libncurses5-dev zlib1g-dev unzip subversion doxygen patch flex
